# Generated by Django 3.1.1 on 2020-12-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=30)),
                ('last_name', models.CharField(default='none', max_length=30)),
                ('email', models.CharField(default='none', max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('username', models.CharField(default='none', max_length=30)),
                ('phone', models.CharField(default='none', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.BooleanField(default=False)),
                ('password', models.CharField(default='none', max_length=30)),
                ('inviter_name', models.CharField(default='none', max_length=30)),
                ('link', models.IntegerField(default=205534)),
                ('shares_income', models.IntegerField(default=0)),
                ('referal_income', models.IntegerField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('inviter_link', models.IntegerField(default=0)),
                ('total_promo', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
