# Generated by Django 3.1.1 on 2020-12-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0002_auto_20201229_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='v_code',
            field=models.IntegerField(default=2134),
        ),
    ]
