# Generated by Django 3.1.1 on 2021-04-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0005_deposit_public_shares_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='none', max_length=30)),
                ('t_type', models.CharField(default='none', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('ref', models.CharField(default='none', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchangeapp.detail')),
            ],
        ),
    ]
