# Generated by Django 3.1.1 on 2021-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='ref',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
