# Generated by Django 3.1.1 on 2021-04-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0007_withdrawal_ref'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Public_shares',
            new_name='Public_share',
        ),
    ]
