# Generated by Django 3.1.1 on 2021-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0009_active_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='buy1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='public_share',
            name='span',
            field=models.BooleanField(default=False),
        ),
    ]
