# Generated by Django 3.1.1 on 2021-04-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0010_auto_20210404_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_share',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
