# Generated by Django 3.1.1 on 2021-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0011_active_share_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='shares_status',
            field=models.BooleanField(default=False),
        ),
    ]
