# Generated by Django 3.1.1 on 2021-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0012_detail_shares_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold_share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('shares_amount', models.IntegerField(default=0)),
                ('shares_value', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('period', models.CharField(default='none', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
