# Generated by Django 3.1.1 on 2021-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0013_sold_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_share',
            name='sale_amount',
            field=models.IntegerField(default=0),
        ),
    ]
