# Generated by Django 3.1.1 on 2021-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0014_sold_share_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_share',
            name='phone',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
