# Generated by Django 3.1.1 on 2021-05-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0020_auto_20210506_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='none', max_length=30)),
                ('name', models.CharField(default='none', max_length=30)),
                ('email', models.CharField(default='none', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchangeapp.detail')),
            ],
        ),
    ]
