# Generated by Django 3.1.1 on 2021-05-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0021_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='mobile',
            new_name='phone',
        ),
    ]
