# Generated by Django 3.1.1 on 2021-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0022_auto_20210506_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='invest1',
            field=models.BooleanField(default=False),
        ),
    ]
