# Generated by Django 3.1.4 on 2021-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_auto_20210629_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnmonline',
            name='amount',
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
